- src/crate/theme/rtd/crate/static/css/main.css
- src/crate/theme/rtd/crate/static/css/main.less
causes breaking of the documentation header when focused
> fix unnecessary focus on search field

- CHANGES.txt
- src/crate/theme/rtd/conf/crate_dbal.py
- src/crate/theme/rtd/conf/crate_pdo.py
- src/crate/theme/rtd/conf/crate_ruby.py
* crate-pdo
* crate-dbal
* crate-ruby
> added more project configurations

- src/crate/theme/rtd/crate/sidebartoc.html
- src/crate/theme/rtd/crate/static/css/crateio-rtd.css
Associated RTD changes reflecting cactus changes @joemoe
> Menu update to reflect new changes

- CHANGES.txt
- src/crate/theme/rtd/crate/layout.html
- src/crate/theme/rtd/crate/static/js/searchtools.js
this relies on:
* https://github.com/rtfd/readthedocs.org/pull/1808
* https://github.com/rtfd/readthedocs-sphinx-ext/pull/16
> host searchtools.js on our theme

- src/crate/theme/rtd/crate/footer.html
> fixed links in footer to exclude .html

- README.rst
> invoke buildout with python, fixes #47

- src/crate/theme/rtd/crate/static/css/crateio-rtd.css
> add caution admonition style

- DEVELOP.rst
- README.rst
this fixes #54 and #55 
it partially addresses #50 and #56. a full fix for this will come after
> refactoring top level docs

- DEVELOP.rst
> fix up formatting issues

- DEVELOP.rst
- buildout.cfg
this pr switches to `twine` for uploading packages, plus a minor copy edit
> use twine for upload, plus minor edit

- src/crate/theme/rtd/crate/static/css/crateio-rtd.css
this adds a blue style for "tip" admonition blocks
also some minor css refactoring
> add style for tips, plus css refactor

- src/crate/theme/rtd/conf/__init__.py
see https://github.com/crate/crate-jdbc/pull/223#discussion_r126800308
> drop explicit favicon config

- src/crate/theme/rtd/crate/static/css/custom.css
- src/crate/theme/rtd/crate/static/js/custom.js
Taking care of a few Trello cards on https://trello.com/b/W207Y10y/website-development relating to the docs. See commits for notes on changes made. All are UI.
> Ui improvements

- src/crate/theme/rtd/crate/footer.html
- src/crate/theme/rtd/crate/navbar.html
We changed the menu structure with the new website refresh.
This is reflected with this PR in the Docs.
We need to rebuild all of them.
> synced docs menu with new website menu structure

- CHANGES.txt
- src/crate/theme/rtd/__init__.py
new release for the menu sync.
> prepare release 0.5.51

- src/crate/theme/rtd/crate/static/css/crateio-rtd.css
I spotted a css bug. this fixes it
> fix admonition style for ul elements

- src/crate/theme/rtd/crate/footer.html
> privacy policy link

- CHANGES.txt
- src/crate/theme/rtd/crate/base.html
- src/crate/theme/rtd/crate/layout.html
> Allow per project css/js files

- CHANGES.txt
- src/crate/theme/rtd/crate/sidebartoc.html
> change depth of toc tree of Cloud CLI project to 2.

- LICENSE
> Berlin address

- src/crate/theme/rtd/crate/footer.html
- deleted community edition 
- added link to CrateDB Editions
> Update Docs Footer

- src/crate/theme/rtd/crate/layout.html
- src/crate/theme/rtd/crate/sidebar.html
- src/crate/theme/rtd/crate/static/css/custom.css
removed scrollbar in sticky slider
> removed scrollbar

- CHANGES.rst
- src/crate/theme/rtd/crate/layout.html
> Changed GitHub shortcut to Ctrl + g

- src/crate/theme/rtd/crate/layout.html
- src/crate/theme/rtd/crate/static/css/crateio.css
Changed the location and appearance of the GitHub-Button
> Eddited Github-Button posision

- DEVELOP.rst
- README.rst
addresses:
- not clear how to prepare change
- not clear how to test changes
- not clear how to get changes live (or who is responsible for that)
> Improve developer docs

- CHANGES.rst
- src/crate/theme/rtd/__init__.py
- src/crate/theme/rtd/crate/layout.html
- src/crate/theme/rtd/crate/static/css/crateio-rtd.css
- src/crate/theme/rtd/crate/static/css/custom.css
css and js changes
there are layout issues on mobile, this should fix at least one of them
> Attempt to fix mobile layout issues

- CHANGES.rst
- docs/conf.py
- src/crate/theme/rtd/crate/layout.html
- src/crate/theme/rtd/crate/static/css/custom.css
- src/crate/theme/rtd/crate/static/js/custom.js
Show GitHub issues for each doc
Added styles for the feedback box (custom.css), functionality (custom.js) and replaced the "Edit on GitHub" button with the box.
> Added Feedback Section

- src/crate/theme/rtd/conf/crate_admin_ui.py
fixes https://github.com/crate/crate-docs-theme/issues/189
> Fix broken URL

- CHANGES.rst
- src/crate/theme/rtd/__init__.py
- src/crate/theme/rtd/conf/__init__.py
https://github.com/crate/tech-writing-domain/issues/11#issuecomment-680053782
> Prepare release 0.10.12

- CHANGES.rst
- docs/requirements.txt
> Dropped unnecessary versioned sphinx requirement specified by docs project

- NOTICE
- Tiny fix to copyright notice as part of review of copyright notices in public repos
> Correction: fix copyright notice

- src/crate/theme/rtd/conf/cloud_howtos.py
- src/crate/theme/rtd/conf/crate_howtos.py
closes https://github.com/crate/tech-writing-domain/issues/317, https://github.com/crate/crate-docs-theme/issues/231
> Improvement: Use shorter project names improve search engine rankings

- src/crate/theme/rtd/crate/layout.html
use the actual page title for page views in segment
> Fix the title in Segment tracking - this was static, now it should use the page title

- CHANGES.rst
Hi there,
this patch retroactively adds some items to the changelog.
Andreas.
> Retroactively update changelog

- docs/images.rst
- docs/index.rst
> Add "images" page for outlining samples of images

- src/crate/theme/rtd/conf/__init__.py
This patch adjusts the linkchecker configuration as suggested by @norosa in order to resolve #230.
> Improve linkchecker configuration

- CHANGES.rst
- src/crate/theme/rtd/conf/cloud_cli.py
- src/crate/theme/rtd/conf/cloud_howtos.py
- src/crate/theme/rtd/conf/cloud_reference.py
- src/crate/theme/rtd/conf/cloud_tutorials.py
- src/crate/theme/rtd/conf/crate_admin_ui.py
- src/crate/theme/rtd/conf/crate_clients_tools.py
- src/crate/theme/rtd/conf/crate_crash.py
- src/crate/theme/rtd/conf/crate_howtos.py
- src/crate/theme/rtd/conf/crate_reference.py
- src/crate/theme/rtd/conf/crate_tutorials.py
- src/crate/theme/rtd/conf/dbal.py
- src/crate/theme/rtd/conf/doing_docs.py
- src/crate/theme/rtd/conf/fake.py
- src/crate/theme/rtd/conf/jdbc.py
- src/crate/theme/rtd/conf/npgsql.py
- src/crate/theme/rtd/conf/pdo.py
- src/crate/theme/rtd/conf/python.py
- src/crate/theme/rtd/conf/sql_99.py
This patch is an attempt to fix #278.
> Improve OpenGraph `og:url` computation

- CHANGES.rst
- src/crate/theme/rtd/crate/static/js/index.js
- src/crate/theme/rtd/crate/static/js/webflow.js
This is an attempt to fix #281. Supersedes #282.
This patch inlines the `webflow.js` file from an earlier revision as we have not been able to find it back anywhere upstream. It weighs in with 140k(!). We should really get rid of this.
> Fix version dropdown by re-adding "Webflow: Front-end site library"

- CHANGES.rst
- src/crate/theme/rtd/conf/__init__.py
> Improve sphinx-copybutton: Also handle "PS>" prompt for Powershell

- CHANGES.rst
- src/crate/theme/rtd/crate/layout.html
this should fix https://github.com/crate/crate-docs-theme/issues/291
> fix title issue for analytics

- .github/workflows/build.yml
- .github/workflows/docs.yml
- DEVELOP.rst
- README.rst
- docs/conf.py
- docs/index.rst
> Rename "master" branch to "main"

- CHANGES.rst
- docs/headings.rst
- src/crate/theme/rtd/__init__.py
- src/crate/theme/rtd/crate/static/css/custom.css
This prepares the release 0.16.0. On a minor note, it also adds a CSS style for `<h7>` HTML headings, provided for corner cases.
> Release 0.16.0

- CHANGES.rst
- src/crate/theme/rtd/conf/__init__.py
- src/crate/theme/rtd/crate/base.html
- src/crate/theme/rtd/crate/footer.html
- src/crate/theme/rtd/crate/layout.html
- src/crate/theme/rtd/crate/navbar.html
- src/crate/theme/rtd/crate/static/css/custom.css
- src/crate/theme/rtd/crate/theme.conf
This is part one of preventing #305 from happening again. I've also added the HubSpot tracking.
Can we test this on one repo first before pushing to all of them? The HubSpot tracking requires an environment variable to be set, can you take care of this, @amotl (pinging you on slack after this).
> Update ESI for HubSpot, introduce TRACKING_HUBSPOT_ID

- CHANGES.rst
- src/crate/theme/rtd/crate/layout.html
- src/crate/theme/rtd/crate/navbar.html
- src/crate/theme/rtd/crate/search.html
- src/crate/theme/rtd/crate/sidebartoc.html
- src/crate/theme/rtd/crate/static/css/custom.css
- src/crate/theme/rtd/crate/static/js/custom.js
- src/crate/theme/rtd/crate/static/js/search.js
- New header (hides when scrolling down, comes back when scrolling up)
- Revamped search (added pagination, number of results, source)
> Improve search and header

- CHANGES.rst
- src/crate/theme/rtd/crate/static/css/crateio.css
> Style: Don't uppercase text, it doesn't look good with the new font

- src/crate/theme/rtd/crate/sidebartoc.html
Tutorials => Install CrateDB: related PR https://github.com/crate/crate-tutorials/pull/77
How-To Guides => CrateDB; related PR https://github.com/crate/crate-howtos/pull/302 (moving getting-started)
> Restructure sidebar

- CHANGES.rst
- src/crate/theme/rtd/__init__.py
- src/crate/theme/rtd/crate/layout.html
- src/crate/theme/rtd/crate/static/js/custom.js
> add height attribute to crate.io logo on sql-99 repo

- CHANGES.rst
- src/crate/theme/rtd/__init__.py
- src/crate/theme/rtd/crate/static/js/custom.js
this should fix the check for anchors
> readded check for hash

- .gitignore
- CHANGES.rst
- Makefile
- package.json
- yarn.lock
What the title says. Probably fixes #353.
> Update JavaScript dependencies across the board

- CHANGES.rst
- src/crate/theme/rtd/crate/footer.html
This will add lazyloading to the footer images, minor SEO thing
> fix missing lazyload for footer images

- src/crate/theme/rtd/conf/__init__.py
This will add the currently missing meta description (copied from the opengraph one)
> add ogp_enable_meta_description = True

- CHANGES.rst
- docs/admonitions.rst
- docs/lists.rst
- setup.py
- src/crate/theme/rtd/__init__.py
- src/crate/theme/rtd/crate/layout.html
- src/crate/theme/rtd/crate/static/css/crateio-rtd.css
Fixes for those regressions in 0.28.0:
- GH-403
- GH-404
> Fix admonition content styles and version chooser

- docs/conf.py
- docs/index.rst
- docs/links.rst
- docs/typography.rst
- src/crate/theme/rtd/conf/theme.py
- src/crate/theme/rtd/crate/sidebartoc.html
- Fix intersphinx links to CrateDB Cloud Docs
- Add demo page about typography details
- Activate navigation for documentation theme project
- Adjust project title
> This and that

- src/crate/theme/rtd/crate/static/css/crateio-ng.css
Makes the container not float in a fixed position when scrolling.
> Fix version chooser/feedback content component position

- CHANGES.rst
- README.rst
- docs/index.rst
- src/crate/theme/rtd/conf/__init__.py
- src/crate/theme/rtd/conf/cloud.py
- src/crate/theme/rtd/conf/cloud_cli.py
- src/crate/theme/rtd/conf/cloud_howtos.py
- src/crate/theme/rtd/conf/cloud_reference.py
- src/crate/theme/rtd/conf/cloud_tutorials.py
- src/crate/theme/rtd/conf/crate_admin_ui.py
- src/crate/theme/rtd/conf/crate_clients_tools.py
- src/crate/theme/rtd/conf/crate_crash.py
- src/crate/theme/rtd/conf/crate_howtos.py
- src/crate/theme/rtd/conf/crate_reference.py
- src/crate/theme/rtd/conf/crate_tutorials.py
- src/crate/theme/rtd/conf/dbal.py
- src/crate/theme/rtd/conf/doing_docs.py
- src/crate/theme/rtd/conf/jdbc.py
- src/crate/theme/rtd/conf/npgsql.py
- src/crate/theme/rtd/conf/pdo.py
- src/crate/theme/rtd/conf/python.py
- src/crate/theme/rtd/conf/sql_99.py
- src/crate/theme/rtd/conf/theme.py
- src/crate/theme/rtd/crate/footer.html
- src/crate/theme/rtd/crate/github_feedback_compact.html
- src/crate/theme/rtd/crate/github_feedback_full.html
- src/crate/theme/rtd/crate/layout.html
- src/crate/theme/rtd/crate/navbar.html
- src/crate/theme/rtd/crate/static/css/custom.css
- src/crate/theme/rtd/crate/version_chooser.html
Migrating to cratedb.com should improve the brand, this is one of the missing steps to get there.
> cratedb.com migration

- CHANGES.rst
- src/crate/theme/rtd/crate/search.html
Better ux when trying to search for things, fixes https://github.com/crate/crate-docs-theme/issues/441
> add autofocus to search input box

- CHANGES.rst
- src/crate/theme/rtd/conf/__init__.py
- src/crate/theme/rtd/crate/base.html
- src/crate/theme/rtd/crate/github_feedback_full.js
- src/crate/theme/rtd/crate/layout.html
- src/crate/theme/rtd/crate/theme.conf
Since we're sunsetting Segment on high traffic pages, this removes it and replaces it with Google Tagmanager
> Remove Segment and replace it with Google Tagmanager

- CHANGES.rst
- src/crate/theme/rtd/crate/footer_sql99.html
- src/crate/theme/rtd/crate/layout.html
This removes part of the footer of the SQL-99 docs and also one CTA from the header.
> Removed CTA, updated footer for SQL-99

- CHANGES.rst
- setup.py
Update to [sphinx-design-elements 0.3.0](https://github.com/pyveci/sphinx-design-elements/releases/tag/v0.3.0).
> Update to sphinx-design-elements 0.3.0

- src/crate/theme/rtd/crate/sidebartoc.html
> Remove the separate "Install" menu item

- src/crate/theme/rtd/crate/sections/sidebar-secondary.html
- src/crate/theme/rtd/crate/static/css/ng/layout.scss
This should ~~bring back the version chooser and also~~ fix some spacing issues.
https://crate-docs-theme--518.org.readthedocs.build/en/518/
> NG: Finetune footer spacing

- src/crate/theme/rtd/crate/sidebartoc.html
> Release 0.34.1

- CHANGES.rst
- src/crate/theme/rtd/crate/sidebartoc.html
- Intends to resolve GH-538.
https://crate-docs-theme--544.org.readthedocs.build/en/544/
> Navigation: Re-add menu item about Cloud CLI (croud)

- README.rst
> README: Add badge informing about compatible Python versions

- CHANGES.rst
- src/crate/theme/rtd/crate/static/css/custom.css
Intends to fix reappearing EthicalAds.
- GH-589
> Disable RTD's EthicalAds by honouring new container id

- src/crate/theme/rtd/crate/base.html
Not many signup via the newsletter. It's visually disturbing and not adding to a good documentation user experience.
Marketing approved of removing this in [Slack](https://crate.slack.com/archives/C07H9U8HL8Z/p1750249512509819?thread_ts=1750232413.455649&cid=C07H9U8HL8Z).
> Removed Marketing news letter signup
