crate/crate-docs-theme

CHANGES.txt
src/crate/theme/rtd/crate/static/js/searchtools.js

I couldn't figure out why the searchindex filenames have .txt extention in rtd (i couldn't reproduce in in crate master)
searchtools.js shouldn't make the assumption that filenames have no suffix and should work for both cases.

Fixed issue that caused the search result links to be broken

---

CHANGES.txt
src/crate/theme/rtd/crate/base.html
src/crate/theme/rtd/crate/footer.html
src/crate/theme/rtd/crate/navbar.html
src/crate/theme/rtd/crate/sidebartoc.html

the problem is that the project name changed from `Crate` to `CrateDB` so this line in the sidebar was returning false `{% if project == 'CrateDB' %}` and there for the tree could not be loaded.
i fixed some formatting issues in some html files, and removed a trailing `</div>`

Fix issue that caused the doc navigation to not be displayed.

---

src/crate/theme/rtd/conf/crate_guide.py
src/crate/theme/rtd/crate/sidebartoc.html

this PR:
- retires the Cactus links
- adds links to the new CrateDB Guide
- reshuffles the organisation of the docs
see: https://trello.com/c/7od7BLjy/74
the menu now looks like this:
the new URLs look like this:
/docs/cratedb/reference (the main CrateDB docs, a reference work)
/docs/cratedb/guide (the new CrateDB guide)
/docs/clients/crash
/docs/clients/python
/docs/clients/java
...
for this to work, we will have to update our fastly config

add CrateDB Guide and reshuffle docs organisation

---

src/crate/theme/rtd/crate/static/js/searchtools.js

It turns out the search results don't use the HTML template in either `searchresults.html` or `search.html`, but generate the markup straight in jQuery. I've edited the jQuery to reflect the correct markup, so the changes should show properly now.

Add search results structure to jQuery func

---

CHANGES.txt
src/crate/theme/rtd/crate/static/css/crateio-rtd.css

I want to start using this:
```
.. contents::
:local:
```
for local tocs. but the style atm adds a 1px border around them which looks bad. this makes local tocs look like regular tocs

remove topic border

---

src/crate/theme/rtd/conf/__init__.py
src/crate/theme/rtd/crate/layout.html

Read the Docs forces its own canonical URL, so to override this, we must set up
the override at a later stage in the Sphinx initialization. Further, because we
use a custom extension ourselves, we have to compete with the order of Sphinx
extension initialization.
No changes should be required to child `conf.py` files, as all the configuration
already exists in the `crate_*.py` config files. Namely, the
`canonical_url_path` theme option should be altered to the correct path.

Force canonical URL override on RTD

---

src/crate/theme/rtd/conf/crash.py
src/crate/theme/rtd/conf/crate_dbal.py
src/crate/theme/rtd/conf/crate_guide.py
src/crate/theme/rtd/conf/crate_java.py
src/crate/theme/rtd/conf/crate_jdbc.py
src/crate/theme/rtd/conf/crate_mesos.py
src/crate/theme/rtd/conf/crate_pdo.py
src/crate/theme/rtd/conf/crate_python.py
src/crate/theme/rtd/conf/crate_ruby.py
src/crate/theme/rtd/conf/crate_server.py

we recently changed our rewrites to always use `en/latest` so this change reflects that in our canonical url settings too

append en/latest to all canonical url paths

---

src/crate/theme/rtd/conf/__init__.py

This wasn't tested against LaTeX builder, and the context data doesn't exist on
this builder. This patch only patches the HTML builder subclasses.

Conditionally apply canonical url patch based on builder type

---

src/crate/theme/rtd/conf/__init__.py

The Epub builder is a StandaloneHtmlBuilder, so passed through our check. It
doesn't have the same html_theme_options, hence the error on builds with epub
output.

Fix build for epub builder

---

CHANGES.txt
setup.py

* We relaunched the Website Refresh yesterday
* We want to have a proper Sitemap setup
* We use https://github.com/jdillard/sphinx-sitemap to build the sitemaps automatically
* We need to get the dependency into the theme before we can change the documentation in the projects

Added dependency to 'sphinx_sitemap' so that we can build sitemaps

---

src/crate/theme/rtd/conf/sql_99.py
src/crate/theme/rtd/crate/sidebartoc.html

this activates the SQL-99 project so that the docs theme can be used by the new docs project. however, the nav link only shows up if you navigate directly to the project. once this is ready for a proper launch, I will change this so it always shows up in the navbar

add sql-99 project (hidden, for now)

---

src/crate/theme/rtd/crate/footer.html

Deleted the Eventhub Integration Page, which is deprecated.

Docs Footer Update

---

README.rst

- We were not clear about the state of this theme.
- It is highly bound to the website of Crate.io and has dependencies on the structure of the documentation.
- It can't just be used for the documentation of other products.

Clarified the intention of the theme

---

CHANGES.rst
src/crate/theme/rtd/crate/layout.html
src/crate/theme/rtd/crate/static/css/crateio.css

Added a view on GitHub button so people reading the Documentation don't have to search for the right repo if they have a problem or want to ask or suggest something.

Adding a view on GitHub button

---

src/crate/theme/rtd/conf/cloud_cli.py
src/crate/theme/rtd/conf/cloud_howtos.py
src/crate/theme/rtd/conf/cloud_reference.py
src/crate/theme/rtd/conf/cloud_tutorials.py
src/crate/theme/rtd/conf/crate_admin_ui.py
src/crate/theme/rtd/conf/crate_clients_tools.py
src/crate/theme/rtd/conf/crate_crash.py
src/crate/theme/rtd/conf/crate_howtos.py
src/crate/theme/rtd/conf/crate_reference.py
src/crate/theme/rtd/conf/crate_tutorials.py
src/crate/theme/rtd/crate/sidebartoc.html

Specifically:
- Fix alignment of project names in Python conf modules and in the
sidebartoc.html template file. This ensures that the TOC menu shows up for all
projects.
- Improve the titling of the projects to take into account the fact they are
used in the HTML `<title>` element and hence show up (most notably) in search
engine result pages.

Fix project names

---

CHANGES.rst
src/crate/theme/rtd/crate/layout.html

1. Only one call instead of two to the GitHub search API, which will help with the rate limit.
2. Removed an analytics.track() call, those aren't supposed to be triggered on every pageview, that's what analytics.page() is for. Added a track call for when the Feedback section is loaded (i.e. when someone scrolls at the end of a doc).

Updated Feedback section & tracking

---

src/crate/theme/rtd/crate/layout.html

The generated links for when someone opens a docs issue needs to have their suffix swapped.
The swap needs to happen for "Page URL" and "Source".  The source links should always end with HTML. 
Note: I wanted to add a note in CHANGES.rst after pulling https://github.com/crate/crate-docs-theme/pull/187

Fix links in the docs issue template

---

CHANGES.rst
src/crate/theme/rtd/conf/__init__.py
src/crate/theme/rtd/crate/layout.html

This should be set up by individual projects, rather than being
hardcoded into the theme itself. Alongside this, if the analytics id
code is not set, the analytics library is not loaded.

Remove tracking segments code from docs theme

---

CHANGES.rst
setup.py

for https://github.com/crate/tech-writing-domain/issues/135

Downgraded Sphinx dependency to 1.8.5 (matches new RTD default)

---

CHANGES.rst
src/crate/theme/rtd/conf/__init__.py
src/crate/theme/rtd/conf/cloud_cli.py
src/crate/theme/rtd/conf/cloud_howtos.py
src/crate/theme/rtd/conf/cloud_reference.py
src/crate/theme/rtd/conf/cloud_tutorials.py
src/crate/theme/rtd/conf/crate_admin_ui.py
src/crate/theme/rtd/conf/crate_clients_tools.py
src/crate/theme/rtd/conf/crate_crash.py
src/crate/theme/rtd/conf/crate_howtos.py
src/crate/theme/rtd/conf/crate_reference.py
src/crate/theme/rtd/conf/crate_tutorials.py
src/crate/theme/rtd/conf/dbal.py
src/crate/theme/rtd/conf/fake.py
src/crate/theme/rtd/conf/jdbc.py
src/crate/theme/rtd/conf/npgsql.py
src/crate/theme/rtd/conf/pdo.py
src/crate/theme/rtd/conf/python.py
src/crate/theme/rtd/conf/sql_99.py

looks like Read The Docs inserts [language](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-language) and [version](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-version) information into the build environment, which makes sense. but it was causing the custom sitemap URLs to have double `en/` components
this PR fixes that problem by changing how project-specific URLs are built, making explicit use of `language` and `version`, as well as setting an explicit [sitemap URL scheme](https://pypi.org/project/sphinx-sitemap/#customizing-the-url-scheme)
everything seems to work locally. but will have to test once a new theme version is cut

Configure sitemap_url_scheme for Read The Docs

---

CHANGES.rst
src/crate/theme/rtd/crate/navbar.html

Since we want to push cratedb-cloud a bit more, the `Try CrateDB` link in the header should directly open the Cloud tab

changed link to createdb-cloud tab

---

CHANGES.rst
src/crate/theme/rtd/crate/static/css/custom.css

This fixes the external link indicator for external images that open in a new window

Excluded images from external link indicator

---

CHANGES.rst
src/crate/theme/rtd/crate/footer.html
src/crate/theme/rtd/crate/navbar.html
src/crate/theme/rtd/crate/static/css/custom.css

adjusted a bit of css to keep the current layout and added the <esi> tags in the nav-files
This will load the header and footer navigation from crate.io's WordPress installation dynamically through fastly. If something changes there, the docs navi should automatically be updated as well. Please test on a single repo first, because there was no way to test the [esi stuff](https://varnish-cache.org/docs/6.5/users-guide/esi.html?highlight=esi) localhost or on staging.

Added WordPress navi as edge side include via Varnish

---

.github/workflows/docs.yml
.gitignore
.mergify.yml
.travis.yml
docs/Makefile
docs/build.json

this PR is a sub-task of https://github.com/crate/tech-writing-domain/issues/353
changes:
- Pins the docs-build to 0.4.0
- Adds a new GitHub Actions workflow for testing the docs
- Modifies the Travis CI configuration to remove the docs tests (and also extend the existing code tests to macOS, as the configuration was already there)
- Adds a Mergify configuration

Upgrade to new build 0.4.0

---

CHANGES.rst
docs/conf.py
setup.py
src/crate/__init__.py
src/crate/theme/rtd/__init__.py
src/crate/theme/rtd/conf/__init__.py
src/crate/theme/rtd/conf/cloud_cli.py
src/crate/theme/rtd/conf/cloud_howtos.py
src/crate/theme/rtd/conf/cloud_reference.py
src/crate/theme/rtd/conf/cloud_tutorials.py
src/crate/theme/rtd/conf/crate_admin_ui.py
src/crate/theme/rtd/conf/crate_clients_tools.py
src/crate/theme/rtd/conf/crate_crash.py
src/crate/theme/rtd/conf/crate_howtos.py
src/crate/theme/rtd/conf/crate_reference.py
src/crate/theme/rtd/conf/crate_tutorials.py
src/crate/theme/rtd/conf/dbal.py
src/crate/theme/rtd/conf/fake.py
src/crate/theme/rtd/conf/jdbc.py
src/crate/theme/rtd/conf/npgsql.py
src/crate/theme/rtd/conf/pdo.py
src/crate/theme/rtd/conf/python.py
src/crate/theme/rtd/conf/sql_99.py
src/crate/theme/rtd/crate/sidebartoc.html

Specifically:
- The `project` variable for both how-to projects was updated in the Python
config files but not the template. This change corrects that issue and adds a
helpful comment above all `project` variable assignments to help avoid this
issue in the future.
- Reformatted all Python files using Black <https://pypi.org/project/black/>.
This was an easy change while I was digging into the Python code.
- Shortened `CHANGES.rst` title to match our current style guide.

Fix sidebar TOC, plus minor code reformatting 

---

docs/index.rst
src/crate/theme/rtd/crate/static/css/custom.css

Specifically:
- Remove the CSS rules that expand bullet point padding when they appear inside
an admonition.
There is no reason for this that I can figure out, it looks bad, it is
inconsistent with list styling outside of admonitions, and it removes the
distinction between closed lists and open lists (see "Lists" section in
https://github.com/crate/crate-docs/blob/main/style/rst.rst)
- Added some test content to `docs/index.rst` that allows you to view how
different lists are styled in different contexts.
Additionally, I reworked the rest of `docs/index.rst` to make it clear this
is a sample Sphinx project we can use to visually test the theme.

Fix styling of lists in admonitions, rework Sphinx project for testing

---

docs/build.json
docs/index.rst

Hi there,
this patch fixes https://github.com/crate/crate-docs/issues/65 reported by @msbt. You can either choose this one, or bring in #245 instead. Or do both, one after the other.
Andreas.

Fix the build by bumping to crate-docs 1.0.0

---

CHANGES.rst
docs/glossary.rst
docs/index.rst
docs/subpage.rst
src/crate/theme/rtd/crate/static/css/custom.css

this PR adds one commitc. the commit messages contain a description of the change

New glossary links styling

---

CHANGES.rst
setup.py

Hi,
Sphinx 4.0.0b1 was released yesterday and I wanted to take the chance to check whether our infrastructure will work on that without further ado. In order to make it installable, we will have to relax the constraints here.
As far as I can see, things are working without any issues. However, we will carefully check the state of the onion as soon as this trickles downstream.
Bumping this will also probably don't do any immediate harm, because, unless explicitly pinned on the dependency chain, RTD will still just use Sphinx 1.8. So, this patch should come without any risks.
Andreas.

Permit installation on Sphinx 4

---

CHANGES.rst
docs/index.rst
docs/links.rst
src/crate/theme/rtd/conf/__init__.py

Hi,
this patch brings the intersphinx mapping from https://github.com/crate/crate-tutorials/pull/47 to where it should actually happen. When adding it here, all references will be available to all downstream repositories without further ado.
Andreas.

Add intersphinx mapping

---

src/crate/theme/rtd/crate/layout.html
src/crate/theme/rtd/crate/static/css/crateio-rtd.css
src/crate/theme/rtd/crate/static/css/crateio.css
src/crate/theme/rtd/crate/static/css/custom.css

Hi,
because the CSS class "`section`" is being used by Sphinx itself to render content sections, it should not be used for general layout aspects.
Thus, this patch introduces a separate class `w-canvas` as an umbrella for the whole content and removes the coupling of the former `w-section` / `section` pairing for this very purpose.
Andreas.

Improve margins

---

src/crate/theme/rtd/crate/footer.html
src/crate/theme/rtd/crate/navbar.html

for navi-newsletter.php and navi-promo.php to dynamically include a promotion header and a newsletter after the footer
with this we can include a dynamic promo header and the newsletter registration in the footer from WordPress

add ESI promo header and newsletter footer

---

docs/admonitions.rst
docs/headings.rst
docs/index.rst
docs/links.rst
docs/lists.rst
docs/subpage.rst

Hi there,
in order to reduce confusion, this patch restructures the sample content that can be used for visually testing the theme. The idea is that each "topic/feature" has a dedicated page.
Andreas.

Restructure sample content

---

docs/lists.rst

Hi @matthijskrul,
this patch adds an auto-enumerated list to the documentation samples in order to verify #256.
Andreas.

Add auto-enumerated list to documentation samples

---

.github/workflows/docs.yml
CHANGES.rst
README.rst
docs/diagrams.rst
docs/index.rst
setup.py
src/crate/theme/rtd/conf/__init__.py

Hi there,
this patch completes the documentation rig with a sample of an UML diagram in order to verify the PlantUML Sphinx addon.
Andreas.

Add PlantUML sample

---

CHANGES.rst
setup.py
src/crate/theme/rtd/conf/__init__.py

Hi there,
this patch adds and activates the Sphinx extension [sphinxext-opengraph](https://github.com/wpilibsuite/sphinxext-opengraph) to generate OpenGraph metadata (https://ogp.me/).
```html
<meta property="og:title" content="Different kinds of diagrams" />
<meta property="og:type" content="website" />
<meta property="og:url" content="https://crate.io/diagrams.html" />
<meta property="og:site_name" content="Crate.io documentation" />
<meta property="og:description" content="PlantUML:" />
<meta property="og:image" content="https://user-images.githubusercontent.com/453543/119536319-3c9ca480-bd89-11eb-908d-3da78e55f17b.png" />
```
Andreas.

Add extension "sphinxext.opengraph"

---

CHANGES.rst
docs/codesnippets.rst
docs/index.rst
setup.py
src/crate/theme/rtd/conf/__init__.py
src/crate/theme/rtd/crate/layout.html
src/crate/theme/rtd/crate/static/css/custom.css

Hi there,
having a sound implementation for copying code snippets from the documentation as outlined within #258 is a longstanding wish. This patch uses the excellent [sphinx-copybutton](https://github.com/executablebooks/sphinx-copybutton) extension as suggested by @msbt. Thank you!
Andreas.
/cc @proddata, @hammerhead, @seut

Add "sphinx-copybutton" extension

---

src/crate/theme/rtd/conf/doing_docs.py
src/crate/theme/rtd/crate/sidebartoc.html

Add `doing_docs` config module (hidden menu item)
This config module will unlock a hidden "Doing Docs at Crate.io" heading in the left-hand navigation menu when the new "Doing Docs at Crate.io" project (currently a [WIP][1]) is accessed directly. This is similar to how a hidden [SQL-99 Complete, Really][2] heading is unlocked when you view that project directly.
The result will be:
- The docs menu is unaltered for all normal visitors, and there is no mention of a "Doing Docs at Crate.io" page.
- People who directly access the "Doing Docs at Crate.io" docs (e.g., via a link from the GitHub [crate-docs][3] project page) will see an additional navigation item titled "Doing Docs at Crate.io". This navigation item is helpful because it will expand to show the content tree, like all other …

Add `doing_docs` config module (hidden menu item)

---

CHANGES.rst
src/crate/theme/rtd/crate/static/css/crateio-rtd.css
src/crate/theme/rtd/crate/static/css/custom.css
src/crate/theme/rtd/crate/theme.conf

Hi there,
this is a first improvement in order to resolve #257. It brings in more contrast in order to improve the typeface to distinguish prose from code.
Andreas.

Use Pygments style "material" for code highlighting

---

CHANGES.rst
src/crate/theme/rtd/conf/__init__.py

Some of the clients docs used an outdated URL pattern containing `clients/`. I noticed this in the output from `make dev`, which alerts you to any redirects encountered. This commit corrects those URLs.

Fix intersphinx project URLs

---

CHANGES.rst
src/crate/theme/rtd/crate/static/css/crateio-rtd.css

- Removed gray border from pre-element
- Added border-radius to highlight-element
- Added small box shadow to highlight-element

Adjust style of highlighted codeblocks: Border, border radius and shadow

---

CHANGES.rst
src/crate/theme/rtd/crate/layout.html

This patch hopefully fixes the problem `Uncaught TypeError: $.cookie is not a function` reported by @msbt at https://github.com/crate/crate-docs-theme/issues/277#issuecomment-849045427.

Fix problem accessing "jquery.cookie" module

---

CHANGES.rst
src/crate/theme/rtd/crate/static/css/crateio.css

- increase top margin to multiple of font-size
- bottom margin half of font-size

Changed top and bottom margins for headings

---

docs/images.rst

Hi there,
because @matthijskrul asked before, this patch demonstrates image scaling on both variants of `.. image` and `.. figure` roles.
Andreas.

Improve samples with ".. image" and ".. figure" roles

---

CHANGES.rst
docs/requirements.txt
setup.py
src/crate/theme/rtd/conf/__init__.py

Hi Naomi,
do you believe this would fit the bill for https://github.com/crate/crate-docs-theme/issues/294? Why we currently need `docutils==0.16` is outlined at #252.
Andreas.

Improve version pinning

---

src/crate/theme/rtd/crate/static/css/custom.css

Previously, when you hovered over the copy button with your mouse, the cursor does not change from the default to indicate that you can click the element. This change makes the cursor switch to the `pointer` style (used to indicate that something is clickable).

Switch copy button cursor to `pointer`

---

CHANGES.rst
docs/codesnippets.rst
setup.py

Currently, empty lines in code snippets will not get copied to the clipboard when using sphinx-copybutton. For example, see https://crate.io/docs/python/en/latest/sqlalchemy.html#tables.
By following up on https://github.com/executablebooks/sphinx-copybutton/issues/84, this patch will resolve #287.
For this to work, https://github.com/executablebooks/sphinx-copybutton/pull/127 will have to be integrated and released beforehand.

Improve sphinx-copybutton: Enable copying empty lines

---

src/crate/theme/rtd/crate/static/css/custom.css

Within highlighted code examples, comments and command outputs are styled with a distinct color. Previously, the contrast between this color and the color of the background was relatively low. Low contrast makes text difficult to read and is an accessibility issue.
This commit increases the luminance of the color while preserving hue. This change improves the contrast and makes the text easier to read.
Color with the old CSS:
- Contrast ratio of 2.43:1
- Fails all WCAG accessibility guidelines
- See https://webaim.org/resources/contrastchecker/?fcolor=546E7A&bcolor=263238
New comment color:
- Contrast ratio of 7.5:1
- Passes all WCAG accessibility guidelines
- See https://webaim.org/resources/contrastchecker/?fcolor=B7C6CD&bcolor=263238

Improve the contrast of highlight comments and command output

---

src/crate/theme/rtd/crate/static/css/custom.css

The existing headings styles are a mismatch, likely due to people making small changes to specific headings over time without much coordination and with no refactoring.
This change refactors the headings styles for `<h2>` through `<h6>` (the only main text headers that we support).
The method I used was to take the largest heading and then scale that down by set percentages, one header at a time.
I have left the calculations used in the CSS file using comments so that future maintainers will:
1. Be able to get an understanding of why and how the headings are set up the way they are
2. Be able to make modifications and then propagate those changes through all headings (maintaining relative consistency)

Improve headings styles

---

.github/workflows/build.yml
Makefile

We had some troubles using Node.js 17, see #307. Using Node.js 14 LTS [1] does not break the build.
```shell
make build
.env/bin/nodeenv --python-virtualenv --node=14.18.1
* Install prebuilt node (14.18.1) ..... done.
. .env/bin/activate && \
printf "Node.js version: "; node --version && \
yarn install && \
npx webpack --mode=production
Node.js version: v14.18.1
yarn install v1.22.17
Checking .dist/crate_docs_theme-0.18.0-py3-none-any.whl: PASSED
Checking .dist/crate-docs-theme-0.18.0.tar.gz: PASSED
```
[1] Installed using [`nodeenv`](https://pypi.org/project/nodeenv/).

Use Node.js 14 LTS for building the distribution package

---

src/crate/theme/rtd/crate/layout.html
src/crate/theme/rtd/crate/sidebar.html
src/crate/theme/rtd/crate/static/css/crateio.css
src/crate/theme/rtd/crate/static/js/search.js

- Search was triggered by default which resulted in searching for null, which is not great for obvious reasons, this should only happen now if a query word is supplied
- Sidebar: when already on `search.html`, you couldn't click the search-link again because it was replaced with `#`
- Layout: Only load the `search.js` when actually visiting the search page, not when api credentials are supplied
- added `background: #fff;` to the version-toggler (in case of overlapping admonitions)

additional search fix

---

CHANGES.rst
src/crate/theme/rtd/conf/__init__.py

Hi,
coming from https://github.com/crate/crate-docs-theme/issues/323, this patch attempts to make _RTD footer and version data injection_ work. Apparently, the `proxied_api_host` context variable can be used to adjust the relevant functionality [^1].
In order to make query string parameters forwarding work, it will need to be accompanied by another patch to the Nginx reverse proxy configuration, see https://github.com/crate/infrastructure/pull/2850.
Andreas.
P.S.: For demonstration purposes, we chose to use the `crate-howtos` project. Without this patch, corresponding requests are directed to [1], which is clearly wrong. Now, requests will hopefully be directed to [2]. This has not been tested yet.
[1] https://crate.io/_/api/v2/footer_html/
[2] …

Attempt to make RTD footer and version data injection work

---

.github/workflows/docs.yml
.gitignore
CHANGES.rst
Makefile
package.json
setup.py
yarn.lock

Just a minor patch for maintenance. I will run a release afterwards to unbreak the documentation builds.
- Bump some JavaScript development dependency versions to satisfy Dependabot.
- Adjust dependencies to use Sphinx<4 and Jinja2<3.1, see also https://github.com/sphinx-doc/sphinx/issues/10291. Thanks, @matthijskrul!
The latter will hopefully fix the builds over at:
- https://github.com/crate/cloud-tutorials/runs/5678664519
- https://github.com/crate/crate-docs-theme/runs/5690254462
```python
ImportError: cannot import name 'environmentfilter' from 'jinja2' (/home/runner/work/crate-docs-theme/crate-docs-theme/docs/.crate-docs/.venv/lib/python3.9/site-packages/jinja2/__init__.py)
```

Adjust some dependency versions

---

CHANGES.rst
src/crate/theme/rtd/__init__.py
src/crate/theme/rtd/conf/__init__.py

Hi,
after #326 didn't quite make it, this is another attempt to fix it. The area where the error was coming from was now validated on behalf of the `crash` project [^1], so at least this patch has more substance than the previous one.
Andreas.
[^1]: While on it, https://github.com/crate/crash/pull/365 has been submitted.

Adjust `proxied_api_host` once more to fix RTD API access

---

CHANGES.rst
src/crate/theme/rtd/conf/__init__.py

The conf.py-wide global `html_context` variable is set by RTD. Now, we also set it locally when running the documentation builds in sandbox mode.
In this way, it is much more easy to toggle different RTD features like disabling the GitHub feedback box.
```python
html_context.update({"display_github": False})
```

Add "html_context" variable to main configuration blueprint

---

CHANGES.rst
src/crate/theme/rtd/crate/layout.html

Fix small typo within header banner.

Fix typo within header banner for "SQL-99 Complete, Really"

---

CHANGES.rst
docs/conf.py
src/crate/theme/rtd/conf/__init__.py
src/crate/theme/rtd/conf/sql_99.py

Hi again,
to make 677874ee183fe2 by @msbt work, this patch is needed for individually disabling the GitHub feedback box on the SQL-99 project.
The reason is that the `html_context` of RTD's Sphinx builder [^1] must be augmented after it has been initialized. We haven't been able to find the place where to actually adjust variables like `display_github` elsewhere.
So, we introduced another generic `html_context_custom` dictionary, where individual projects can drop customized settings into. Those settings will then be propagated to the RTD Sphinx builder appropriately, essentially overwriting the previous default settings.
Andreas.
[^1]: https://github.com/readthedocs/readthedocs.org/blob/main/readthedocs/doc_builder/backends/sphinx.py

Add an option to adjust the `html_context` of individual projects

---

CHANGES.rst
src/crate/theme/rtd/conf/__init__.py

This patch attempts to fix a regression reported by @msbt at #342 - thanks again.
In May 2022, RTD changed that static resources are no longer included from https://assets.readthedocs.org/, because it often gets blocked by ad blockers or browser privacy extensions like Privacy Badger.
This patch adjusts the machinery to properly compute the correct URL on the crate.io domain, which is at `f"{html_baseurl}/_/static/"`.
References:
- https://github.com/readthedocs/readthedocs.org/issues/7273
- https://github.com/readthedocs/readthedocs.org/pull/9168
- https://github.com/crate/crate-docs-theme/issues/342

Fix `proxied_static_path` context variable following an RTD update

---

CHANGES.rst
docs/codesnippets.rst
src/crate/theme/rtd/conf/__init__.py

This is a fix for #354, following @msbt's suggestion to add the `copybutton_line_continuation_character = "\\"` configuration setting.

Fix copying multi-line console snippets with `sphinx-copybutton`

---

CHANGES.rst
package.json
src/crate/theme/rtd/crate/layout.html
src/crate/theme/rtd/crate/static/js/index.js
yarn.lock

The most recent version of `jquery-cookie` was published 8 years ago already. On the other hand, `js-cookie` is still being maintained.

Replace `jquery-cookie` with `js-cookie`

---

CHANGES.rst
webpack.config.js

Fix webpack expose configuration for `js-cookie` library

---

CHANGES.rst
src/crate/theme/rtd/crate/static/js/index.js

Hi again,
#359 did not fix the problem. This is another attempt, based on findings at [^1] and [^2].
Andreas.
[^1]: https://github.com/js-cookie/js-cookie/issues/201#issuecomment-971261916
[^2]: https://stackoverflow.com/questions/59234564/how-to-correctly-require-js-cookie-with-npm-and-webpack-uncaught-referenceerror

Fix `js-cookie` library import

---

.github/workflows/docs.yml
.gitignore
MANIFEST.in
Makefile
package.json
requirements.txt
setup.py
yarn.lock

What the title says.
- Add testing on Python 3.11.
- Update JavaScript development dependencies.
- A few updates to the sandbox / project tooling.

Maintenance iteration, with dependency version bumping

---

CHANGES.rst
src/crate/theme/rtd/crate/static/css/crateio-rtd.css

This patch originates from https://github.com/crate/crate-python/pull/487. It tweaks the `xref` CSS class so that it does not render links in bold text when using a custom label. Happens, for example, with `:class:dictionaries <py:dict>`.

Fix visual appearance of Intersphinx references per `xref` CSS

---

.mergify.yml

The Mergify configuration used the deprecated `rebase_fallback` mode of the queue and/or merge action.
- https://docs.mergify.com/actions/queue/#queue-action
- https://github.com/crate/crate/pull/13483/checks

mergify: Remove deprecated `rebase_fallback` option

---

CHANGES.rst
src/crate/theme/rtd/crate/static/css/custom.css

This removed the `code`-tag from the mobile media query which would change the font-size.
Embedded `code` markup within headlines has been assigned an unfortunate font size within the styling variant for smaller devices.
-- https://crate-python--553.org.readthedocs.build/en/553/by-example/sqlalchemy/dataframe.html#efficient-insert-operations-with-pandas

remove code-tag from mobile override

---

CHANGES.rst
src/crate/theme/rtd/crate/static/css/custom.css

Handing in GH-374 again because there have been troubles before.

Fix "font with `code` attribute too small in headline on mobile" flaw

---

CHANGES.rst
src/crate/theme/rtd/__init__.py

Publish new release with updates from GH-374/GH-375.
_Failing tests on CI can probably be attributed to Azure infrastructure.
-- https://github.com/actions/runner-images/issues/7048#issuecomment-1548182826_

Release 0.27.1

---

.readthedocs.yml
Makefile
README.rst
docs/Makefile
docs/index.rst

There is a chicken-egg problem when running RTD preview builds on pull requests with this repository. A **release version** of the corresponding Python package already ships the bundled assets. However, the **development version** does not.
The CI build on RTD needs to bundle resources using webpack before running the build.

CI: Make rendering on RTD on-PR builds work

---

src/crate/theme/rtd/crate/static/css/crateio-rtd.css

This removes the css overrides from the old template to allow new features to work. I also removed the margin-bottom of the last paragraph so the blockquotes are always centered.
https://github.com/crate/crate-docs-theme/pull/378#discussion_r1265560168 for reference

remove blockquote overrides

---

.github/workflows/build.yml
.github/workflows/docs.yml
CHANGES.rst
docs/conf.py
src/crate/theme/rtd/crate/github_feedback_full.html
src/crate/theme/rtd/crate/github_feedback_full.js
src/crate/theme/rtd/crate/github_keynav.js
src/crate/theme/rtd/crate/layout.html
src/crate/theme/rtd/crate/static/css/crateio-ng.css
src/crate/theme/rtd/crate/static/css/crateio.css
src/crate/theme/rtd/crate/static/css/index.css
src/crate/theme/rtd/crate/static/js/index.js
src/crate/theme/rtd/crate/static/js/util.js
src/crate/theme/rtd/crate/version_chooser.html

Use separate files for defining the feedback component at the bottom of the page, and the version chooser at the top of the page.
It aims to set the stage for GH-385, which actually changes the page layout. This patch only moves code around, and starts building upon modern styling components, without changing the visual appearance too much.
https://crate-docs-theme--384.org.readthedocs.build/en/384/
- https://github.com/crate/crate-docs/pull/99 will make it easier to work on such refactorings, by also triggering automatic rebuilds on changes to HTML, CSS, and JS files.

Refactor feedback and version chooser components

---

CHANGES.rst
src/crate/theme/rtd/crate/static/css/custom.css

The example at [^1] clearly shows why the external links indicator is annoying. This patch removes it.
See [^2].
[^1]: https://crate-docs-theme.readthedocs.io/en/latest/rst/infocard.html#example-3
[^2]: https://crate-docs-theme--386.org.readthedocs.build/en/386/rst/infocard.html#example-3

Remove external links indicator

---

CHANGES.rst
docs/admonitions.rst
docs/index.rst
src/crate/theme/rtd/crate/static/css/crateio-rtd.css
src/crate/theme/rtd/crate/static/css/crateio.css
src/crate/theme/rtd/crate/static/css/custom.css

Another reason why the look&feel of our documentation is a bit clunky sometimes, are the very bold/large/wide appearances of the admonition components, obstructing the reading flow [^1].
In order to save screen space for main content, this patch aims to tame them a bit, and render them in a more compact style, similar to how those are [originally rendered](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#paragraph-level-markup), and also on [other themes](https://pradyunsg.me/furo/reference/admonitions/).
However, we retain the [hero-/jumbotron-style](https://getbootstrap.com/docs/4.1/components/jumbotron/), as it is valuable for calling extra attention to featured content or information, which may have been the original intention of their bold design. Such …

Improve visual appearance of admonition components

---

CHANGES.rst
src/crate/theme/rtd/conf/cloud.py

CrateDB Cloud documentation has been refactored into a [consolidated repository](https://github.com/crate/cloud-docs) by @matkuliak, thanks. This patch adds a corresponding slot to the backbone.
Because of chicken-egg problems, this needs to be separated from GH-391, and properly released before, to make downstream projects follow in lock-step.

Add new `cloud-docs` documentation project

---

CHANGES.rst
src/crate/theme/rtd/crate/footer.html

This removes the ESI of the footer and replaces it with the regular meta navigation that we were already using on SQL-99. While doing that, I also saw a typo and corrected links, this should be fixed with this PR. The newsletter module is now also above the navigation.

Adjust footer navigation after web site update

---

CHANGES.rst
docs/links.rst
src/crate/theme/rtd/conf/__init__.py
src/crate/theme/rtd/crate/sidebartoc.html

This adjusts a few sections of the primary navigation component.
- The CrateDB Cloud documentation has been refactored into the consolidated [cloud-docs](https://github.com/crate/cloud-docs) repository.
- While integrating it, move `CrateDB Cloud` menu item up [^1].
- Rename link label `Install CrateDB` to `Self-Managed`.
- Rename link label `CrateDB` to `Getting started`.
- Rename link label `Reference` to `Reference Manual`.
- Dissolve section C, listing individual drivers. This section has been reworked within the `Clients, Drivers, and Tools` section, and is much better presented now.
- Add two more links to bottom section D: `Community`, and `Integration Tutorials`.
https://crate-docs-theme--391.org.readthedocs.build/en/391/
A few iterations, from left to right.
With GH-390, we will …

Install consolidated Cloud Docs, and edit primary navigation section in left sidebar

---

setup.py
src/crate/theme/rtd/crate/static/css/crateio-ng.css

- Dependencies: Don't install `docutils-stubs` at runtime.
- UI: Increase `z-index` of feedback chooser content, addressing GH-413.

Last minute fixes

---

CHANGES.rst
src/crate/theme/rtd/crate/github_feedback_compact.html
src/crate/theme/rtd/crate/version_chooser.html

There is a slight problem with that margin of the new "page tools" element, which bumps into the text/content section. It is not so bad when it is collapsed, but when expanding it, it wobbles the text around.

Fix margin on page tools element

---

CHANGES.rst
docs/myst/togglebutton.md
docs/rst/crossref.rst
docs/rst/image-figure.rst
docs/rst/togglebutton.rst
src/crate/theme/rtd/crate/base.html
src/crate/theme/rtd/crate/layout.html

Updating the mechanics of JS/CSS asset includes based on Sphinx 3 and newer. For including assets within HTML templates, the `js_tag()` and `css_tag()` helper functions are now available within the HTML context.
- https://github.com/sphinx-doc/sphinx/blob/master/sphinx/themes/basic/layout.html
- https://github.com/sphinx-doc/sphinx/blob/master/sphinx/themes/classic/layout.html
```javascript
Uncaught ReferenceError: toggleOpenOnPrint is not defined
Uncaught ReferenceError: togglebuttonSelector is not defined
```
```html
<script type="text/javascript" src="None?ver=0.29.0"></script>
<script type="text/javascript" src="None?ver=0.29.0"></script>
<script type="text/javascript" src="None?ver=0.29.0"></script>
```
- GH-383

Modernize and fix JS and CSS includes, and extend demo pages

---

CHANGES.rst
setup.py
src/crate/theme/rtd/crate/layout.html

> Both the settings and version flyout menus can be opened at the same time. Perhaps opening one menu should close the other open menu.
Resolved using an extension to [sphinx-design dropdowns](https://sphinx-design.readthedocs.io/en/latest/dropdowns.html), implementing a similar behavior like [using CSS toggle-group to group exclusive toggles](https://blog.logrocket.com/advanced-guide-css-toggle-pseudo-class/#using-toggle-group-exclusive-toggles), based on a JavaScript implementation provided by @msbt. Thanks!
https://crate-docs-theme--419.org.readthedocs.build/en/419/
- GH-413
- GH-417
- https://github.com/panodata/sphinx-design-elements/pull/15
- https://github.com/panodata/sphinx-design-elements/pull/19

Fix pagetools dropdown: Group elements to define mutual toggle-opening

---

CHANGES.rst
src/crate/theme/rtd/crate/version_chooser.html

When switching versions, the version chooser lost track of the current page. This patch intends to fix it, as suggested by @hlcianfagna. Thank you!
- GH-408

Improve version chooser to use the same page when switching versions

---

CHANGES.rst
docs/build.json
src/crate/theme/rtd/crate/static/css/crateio-ng.css

This patch fixes GH-421. The text within a sphinx-togglebutton admonition was slightly misaligned. Thanks, @msbt.

Fix text alignment with sphinx-togglebutton

---

src/crate/theme/rtd/crate/static/css/custom.css

The new template has smaller icons, SQL-99 overrides that somehow, this should fix it.

Fix minor admonition regression on SQL-99 repo

---

CHANGES.rst
docs/myst/infocard.md
docs/rst/infocard.rst
src/crate/theme/rtd/crate/static/css/crateio.css

fix for https://github.com/crate/crate-docs-theme/issues/382

Fix CSS: Remove font size of blockquote override

---

CHANGES.rst
src/crate/theme/rtd/crate/version_chooser.html

Based on the suggestion from @hlcianfagna (thanks!) at https://github.com/crate/crate-docs-theme/issues/408#issuecomment-1696938367, this patch removes the ambiguous link on the "current" version, which points to the root document, altogether.
https://crate-docs-theme--428.org.readthedocs.build/en/428/

Improve version chooser: Remove ambiguous link on "current" version to root document

---

CHANGES.rst
src/crate/theme/rtd/crate/sidebartoc.html

Fix GH-426. Removing the navigation items to the database drivers with 490ac7e6587 was a silly idea.
This patch brings them back, but nests them within the "Drivers and Integration" section, so they do not take screen space when browsing the other sections. Effectively, it is still a net improvement compared to the original situation.
No preview available. Needs to be rendered by either `crate-clients-tools`, or other database driver projects.

Bring back lost navigation items to database drivers

---

CHANGES.rst
src/crate/theme/rtd/crate/sidebartoc.html

Another attempt to fix the primary navigation on the database driver section.
While GH-429 brought back the navigation items to the database drivers, it is still not quite right, when actually using them.

Improve primary navigation on the database driver section once more

---

CHANGES.rst
src/crate/theme/rtd/crate/version_chooser.html

Improve the version chooser component, in order not to produce invalid HTML links, which yield "404 Not Found" responses when following them, see https://github.com/crate/crate-docs-theme/issues/408#issuecomment-1705711364.
It will stop rendering any links into HTML at all, and use JavaScript instead, using relevant helpers from `pydata-sphinx-theme`. In this way, search engines will hopefully stop picking up the corresponding invalid links.
As a side effect, because the navigation process can be intercepted, users will not be redirected to invalid resources as well, but will be redirected to the documentation root instead.
@drammock and all contributors, thank you so much!
- https://github.com/pydata/pydata-sphinx-theme/pull/436

Add version chooser JavaScript helpers derived from pydata-sphinx-theme

---

CHANGES.rst
src/crate/theme/rtd/crate/github_feedback_compact.html
src/crate/theme/rtd/crate/search.html

For example, the `search.html` page does not need it, and produces links yielding "404 Not Found" responses.
This patch intends to fix GH-437.

Stop displaying the edit/view source link on synthetic pages

---

CHANGES.rst
src/crate/theme/rtd/crate/sidebartoc.html

Apparently, "Cloud Docs" pulled too many levels of page headings into the primary navigation menu (three). This patch decreases that to use only two levels.

Primary navigation: Use `maxdepth=2` for serving "CrateDB Cloud"

---

src/crate/theme/rtd/crate/sidebartoc.html

We found an agreement about a label. What the title says.

Leftnav: Use `Installation` instead of `Self-Managed`

---

CHANGES.rst
src/crate/theme/rtd/conf/sql_99.py
src/crate/theme/rtd/crate/layout.html

after removing SQL-99 [from the docs](https://github.com/crate/crate-docs-theme/pull/453), there are some internal URL issues going on, this is an attempt to fix them.

attempt to fix urls on sql-99 pages

---

.github/workflows/docs.yml
CHANGES.rst
setup.py

... by updating to sphinx-design-elements 0.3.1.
Effectively, relax pinning "sphinx-design-elements<1" so fixes can arrive more quickly, shifting the responsibility about running breaking changes to sde, needing to bump to 1.0.0 if any.

Fix compatibility issue with Python 3.8

---

src/crate/theme/rtd/crate/static/css/crateio-ng.css

Recent deliveries of documentation resources include an annoying overlay on the bottom left corner, which is constantly trying to capture attention, by collapsing/fading in and out of the page border.

UI: Visually disable annoying "notificatio-pro" component

---

CHANGES.rst
src/crate/theme/rtd/conf/__init__.py
src/crate/theme/rtd/conf/cratedb_guide.py

This patch intends to fix a problem introduced with the most recent medium-sized cleanup/refactoring of Crate ./. Sphinx ./. RTD documentation intrinsics.
- GH-489

Fix downstream behavior on "not versioned" projects like CrateDB Guide

---

CHANGES.rst
src/crate/theme/rtd/crate/github_feedback_compact.html
src/crate/theme/rtd/crate/github_feedback_full.html

As the title suggests, this fixes URLs to GitHub feedback (removed hardcoded `https://cratedb.com/`)

Fix URLs to GitHub feedback

---

CHANGES.rst
src/crate/theme/rtd/conf/__init__.py
src/crate/theme/rtd/conf/sqlalchemy_cratedb.py
src/crate/theme/rtd/crate/sidebartoc.html

The [CrateDB SQLAlchemy dialect](https://github.com/crate-workbench/sqlalchemy-cratedb) needs more love, so it was separated from the [DBAPI HTTP driver](https://github.com/crate/crate-python). This patch intends to accompany the migration, by slotting the documentation into the documentation tree.
The new canonical package for the SQLAlchemy CrateDB dialect on PyPI is:
> https://pypi.org/project/sqlalchemy-cratedb/
/cc @matriv, @surister

Add documentation project `sqlalchemy-cratedb`

---

CHANGES.rst
src/crate/theme/rtd/crate/sidebartoc.html
src/crate/theme/rtd/crate/static/css/crateio-ng.css

Add menu item for new top-level landing page, indexing the main docs entrypoints.
- https://github.com/crate/cratedb-guide/pull/94

Menu item for top-level documentation home

---

src/crate/theme/rtd/crate/static/vendor/furo/scripts/furo.js
src/crate/theme/rtd/crate/static/vendor/furo/scripts/gumshoe-patched.js
src/crate/theme/rtd/crate/static/vendor/furo/styles/_scaffold.sass
src/crate/theme/rtd/crate/static/vendor/furo/styles/base/_screen-readers.sass
src/crate/theme/rtd/crate/static/vendor/furo/styles/base/_theme.sass
src/crate/theme/rtd/crate/static/vendor/furo/styles/components/_index.sass
src/crate/theme/rtd/crate/static/vendor/furo/styles/components/_search.sass
src/crate/theme/rtd/crate/static/vendor/furo/styles/components/_sidebar.sass
src/crate/theme/rtd/crate/static/vendor/furo/styles/components/_table_of_contents.sass
src/crate/theme/rtd/crate/static/vendor/furo/styles/variables/_fonts.scss

@msbt updated to Furo 2024.5.6. Thanks! This patch updates corresponding vendorized styles.
https://crate-docs-theme--508.org.readthedocs.build/en/508/
In order to update to the most recent sources of Furo, best matching the relevant version in `setup.py`, run this procedure:
```
git clone https://github.com/pradyunsg/furo
cd furo
git checkout 2024.05.06
cd src/furo/assets
cp -r * /path/to/crate-docs-theme/src/crate/theme/rtd/crate/static/vendor/furo/
```
Then, commit the changed files selectively.

NG: Update Furo styles and scripts to version 2024.05.06

---

src/crate/theme/rtd/crate/static/css/custom.css

Override `word-break` to avoid collapsing `dt`'s by full-width `dd`'s 

---

CHANGES.rst
setup.py
src/crate/theme/rtd/conf/__init__.py
src/crate/theme/rtd/crate/static/css/custom.css
src/crate/theme/vendor/rtd_compat/extension.py
src/crate/theme/vendor/rtd_compat/utils.py

- Upstream changes at RTD needed various compensations.
https://about.readthedocs.com/blog/2024/07/addons-by-default/
- Fix version chooser & feedback box.
- https://github.com/crate/crate-docs-theme/issues/536
- https://github.com/crate/cratedb-guide/pull/126

RTD: Add compatibility fixes for upstream changes at Read The Docs

---

src/crate/theme/rtd/crate/sections/header.html
src/crate/theme/rtd/crate/static/css/crateio.css
src/crate/theme/rtd/crate/static/css/custom.css

We want to bring the top navigation from main page to the docs:
- Product
- Use cases
- Industries
- Resources 
- Pricing
https://crate-docs-theme--534.org.readthedocs.build/en/534/
-----
cc @geragray

Navigation: Add header menu items from website

---

.github/workflows/build.yml
.github/workflows/docs.yml
.readthedocs.yml
README.rst
setup.py
src/crate/__init__.py

Verify support for Python 3.13.
Also, [migrate to use "implicit namespace packages" (PEP 420)](https://github.com/crate/crate-docs-theme/commit/1007fca040) for all people who install the theme alongside a Python package that also uses the `crate` namespace. Otherwise, your Python may trip when importing packages.
```python
ModuleNotFoundError: No module named 'crate.client'
```
See also [Package Discovery and Namespace Package » Finding namespace packages](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#namespace-packages).

Python: Use Python 3.13 on CI

---

src/crate/theme/rtd/crate/sidebartoc.html

Fix the last link pointing to crate.io here.

Chore: Use community.cratedb.com instead of previous crate.io

---

CHANGES.rst
setup.py

- [Python: Set minimum Python version to 3.9](https://github.com/crate/crate-docs-theme/commit/df0f8513c7e14388a2ff9acebf8aa0d078076b0c)
- [Dependencies: Remove docutils package from runtime dependencies](https://github.com/crate/crate-docs-theme/commit/4764da0d2ba4dbcbee9072390b2372c04efe7f83)
- [Update changelog](https://github.com/crate/crate-docs-theme/commit/1fba3b0eb8cc96c9e0f66a48c7cfef1dfad7d6f9)

Chore: Adjust Python version. Trim list of dependencies. Update changelog.

---

src/crate/theme/rtd/crate/base.html
src/crate/theme/rtd/crate/page.html
src/crate/theme/rtd/crate/partials/_head_css_variables.html
src/crate/theme/rtd/crate/static/css/ng/index.scss
src/crate/theme/rtd/crate/static/vendor/furo/styles/base/_theme.sass
src/crate/theme/rtd/crate/static/vendor/furo/styles/variables/_index.sass
src/crate/theme/rtd/crate/static/vendor/furo/styles/variables/colors.scss

After introducing dark mode, we recognized white flashes when navigating between pages. This patch should fix it. It wasn't trivial, since some of the logic was custom and some came from furo. I ended up migrating more bits from furo in our template and also updated our `page.html` and `base.html` to make it more compatible.
Quite a bit has changed, so this needs to have proper review again before releasing wide (e.g. canonical links)
Demo is here: https://crate-docs-theme--554.org.readthedocs.build/en/554/
cc @geragray @kneth

Fix white flashes on dark mode 

---

CHANGES.rst
src/crate/theme/rtd/crate/sidebartoc.html

@widmogrod asked at https://github.com/crate/cloud-docs/pull/88#pullrequestreview-2469805836:
> As for the All features page, what I found confusing is the duplication of sub-sections:
> Is there a way to change it, and have all features more like a landing page that just list them?

CrateDB Cloud: Collapse navigation items on `feature/index` page

---

src/crate/theme/rtd/crate/base.html
src/crate/theme/rtd/crate/partials/_head_css_variables.html
src/crate/theme/rtd/crate/sidebartoc.html
src/crate/theme/rtd/crate/static/css/custom.css
src/crate/theme/rtd/crate/static/js/custom.js
src/crate/theme/rtd/crate/static/vendor/furo/scripts/furo.js
src/crate/theme/rtd/crate/static/vendor/furo/styles/base/_theme.sass
src/crate/theme/rtd/crate/static/vendor/furo/styles/variables/_theme.scss
src/crate/theme/rtd/crate/static/vendor/furo/styles/variables/colors.scss

- Fix some regressions from Furo (Algolia focus)
- Remove input focus (inherited from Furo)
- CLS fix from Algolia implementation
- Reposition code block (didn't cascade right)
- Add horizontal scrolling to tables on mobile to avoid having layouts wider than the screen
- Keep iframe embeds from having a layout wider than the screen by adding `max-width`
- Fix scrollbar light-colors on Chromium browsers and different modes
- Use `<html>` instead of `<body>` as target for dark/light mode `data-theme` attributes
Demo: https://crate-docs-theme--560.org.readthedocs.build/en/560/

Fixes for various bugs (scrollbar, focus, cascades), style improvements

---

docs/Makefile

Well, let's use Python 3 today.
```
$ make dev
/bin/sh: python: command not found
Makefile:92: *** No build version specified in `build.json`..  Stop.
```
```diff
-    python -c 'import json, sys; print(json.load(sys.stdin)["message"])')
+    python3 -c 'import json, sys; print(json.load(sys.stdin)["message"])')
```
NB: Makefile has been copied from its [designated original source](https://github.com/crate/crate-docs/blob/main/docs/Makefile), where it is maintained. There is currently no automation to distribute it to downstream projects, because updates are rare.

Chore: Update to use most recent `Makefile` from `crate-docs`

---

.gitignore
CHANGES.rst
docs/myst/cell.md
docs/myst/notebook-text.md
docs/myst/notebook-traditional.ipynb
docs/rst/cell.rst
docs/rst/notebook-text.rst
docs/rst/notebook-traditional.ipynb
setup.py
src/crate/theme/rtd/conf/__init__.py
src/crate/theme/rtd/crate/static/css/custom.css

The documentation can now include traditional Jupyter Notebooks in .ipynb format, as well as [text-based notebooks](https://myst-nb.readthedocs.io/en/latest/authoring/text-notebooks.html) written in Markdown, per [MyST-NB].
By streamlining running SQL and plotting large datasets in Jupyter Notebooks, CrateDB can provide details closer to [what others are offering](https://docs.arangodb.com/stable/arangograph/notebooks/), per [JupySQL].
The patch adds two addons to the documentation stack.
- [MyST-NB] is a gateway from Markdown to IPython/Jupyter: https://github.com/crate/crate-docs-theme/issues/449
- [JupySQL] is a gateway from SQL to IPython/Jupyter via `%sql`, `%%sql`, and `%sqlplot` magics: https://github.com/crate/tech-writing/issues/415
- [Notebook …

Add MyST-NB for rendering notebooks, and JupySQL for running SQL

---

CHANGES.rst
docs/myst/notebook-text.md
docs/myst/notebook-traditional.ipynb
docs/myst/video.md
docs/rst/video.rst
setup.py
src/crate/theme/rtd/conf/__init__.py

Sphinx pages and Jupyter Notebooks can have video embeds, too.
1. There was a question in the audience about whether Sphinx/MyST-NB can display videos from YouTube embedded into the Jupyter Notebook at hand.
2. We started embedding videos on the [CrateDB Guide](https://cratedb.com/docs/guide/) already, but only used inline HTML up until now.
This patch intends to make it proper, by adding relevant Sphinx plugins [oEmbedPy] and [sphinxcontrib-youtube] to the stack.
- Traditional page: [myst/video.html](https://crate-docs-theme--568.org.readthedocs.build/en/568/myst/video.html)
- Traditional Jupyter Notebook: [myst/notebook-traditional.html#video-embeds](https://crate-docs-theme--568.org.readthedocs.build/en/568/myst/notebook-traditional.html#video-embeds)
- Text-based Jupyter Notebook: …

Add `oEmbedPy` and `sphinxcontrib-youtube` for embedding videos

---

docs/myst/oembed.md
docs/myst/video.md
docs/rst/oembed.rst
docs/rst/video.rst

- [oEmbed: Add dedicated page](https://github.com/crate/crate-docs-theme/commit/6bc3de432bd95e51d09fc5ba510e7aa0efa812b5) ([preview](https://crate-docs-theme--570.org.readthedocs.build/en/570/myst/oembed.html))
- [Video: Add Vimeo example, and refer to oEmbed page](https://github.com/crate/crate-docs-theme/commit/f95b92d45d806c9aa34169527cc6811b481ac7c7) ([preview](https://crate-docs-theme--570.org.readthedocs.build/en/570/myst/video.html))
Embedding a few messages by @simonprickett. Thanks!

Docs: oEmbed and Video

---

CHANGES.rst
Makefile

Bump sandbox from Node.js 18 to Node.js 22.
_Non-blocking._
@msbt: The `make bundle-develop` step bears a few deprecation warnings (see [RTD build 26963098](https://readthedocs.org/projects/crate-docs-theme/builds/26963098/)). It is probably on Furo to fix most of them?

Sandbox: Update build environment to use Node.js 22

---

src/crate/theme/rtd/crate/static/css/custom.css

There's no hover effect on the odd `tr`s, this fixes it (original PR https://github.com/crate/crate-docs-theme/pull/566 - https://crate-docs-theme--566.org.readthedocs.build/en/566/myst/notebook-traditional.html for non-working demo).

CSS: Add hover color for tr overrides from #566

---

.github/workflows/build.yml
.github/workflows/docs.yml
.readthedocs.yml
docs/requirements.txt

Add the `uv` program to the toolbox, in this case to speed up documentation rebuilds, both on GHA and RTD.
`uv` is very versatile, and provides better support to work with virtualenvs in different situations, unique support for one-off scripts with inline dependencies, and much more.
- https://docs.astral.sh/uv/
- https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-uv
- https://github.com/readthedocs/readthedocs.org/issues/11289
- https://github.com/astral-sh/uv/issues/10941

CI: Use `uv` package and project manager on GHA and RTD

---

src/crate/theme/rtd/conf/__init__.py

www.gnu.org regularly rejects connections on our documentation (re-)builds.
"It happens more often than not" would be the wrong assessment, but still it's annoying when documentation updates or rebuilds go south on this, and frequency seems to be increasing with gnu.org. Its connectivity displays intermittently flaky, probably due to WAF technologies used to deter knowledge scraping bots, probably aiming to learn and understand the Linux userspace.
```
(performance/inserts/bulk: line  295)       broken    https://www.gnu.org/software/gzip/ - HTTPSConnectionPool(host='www.gnu.org', port=443): Max retries exceeded with url: /software/gzip/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9e09d492d0>: Failed to establish a new connection: [Errno 101] Network …
```

Chore: Add www.gnu.org to global link checker ignores

---

CHANGES.rst
setup.py
src/crate/theme/rtd/conf/__init__.py

The most recent oEmbedPy 0.8 raised errors, so let's downgrade to 0.7.
- https://github.com/crate/crate-docs-theme/issues/586
- https://github.com/attakei/oEmbedPy/issues/9

Dependencies: Fix oEmbedPy by downgrading to version 0.7

---

CHANGES.rst
src/crate/theme/vendor/rtd_compat/extension.py

Make less requests to RTD's API, to avoid failing builds due to [dog-piling effects](https://en.wikipedia.org/wiki/Cache_stampede).
- https://github.com/crate/crate-docs-theme/pull/595#pullrequestreview-2747135403
- GH-553

Improve vendorised `sphinx-build-compatibility` to make less requests to RTD's API

---

src/crate/theme/vendor/rtd_compat/extension.py

- Another patch like GH-596.
Let's skip acquiring project versions when running the link checker.
This avoids hammering the RTD API when rebuilding _all_ docs.

Improve vendorised `sphinx-build-compatibility` not calling RTD API on link checks

---

CHANGES.rst
src/crate/theme/rtd/crate/base.html

Changed the rel attribute from "shortcut icon" to "icon" to make sure Google can index our favicon. See: https://developers.google.com/search/docs/appearance/favicon-in-search

Fix favicon HTML

---

CHANGES.rst
setup.py

See problem described [here](https://github.com/crate/crate-docs/pull/115)

pin sphinx-sitemap extension due to build warnings

---

CHANGES.rst
docs/projects.rst
src/crate/theme/rtd/conf/__init__.py
src/crate/theme/rtd/crate/sidebartoc.html

Content from https://github.com/crate/crate-clients-tools has been migrated to https://github.com/crate/cratedb-guide.
- https://github.com/crate/cratedb-guide/pull/221
- https://github.com/crate/cratedb-guide/pull/222

Phase out `crate-clients-tools`

---

CHANGES.rst
src/crate/theme/vendor/rtd_compat/extension.py

The RTD API behaves flaky again, possibly by becoming increasingly overloaded. The "ignore" fallback added the other day did not work because, well, in this environment, warnings become errors.
```
WARNING: An error occurred when hitting API to fetch active versions. Defaulting to an empty list.
```
-- https://github.com/crate/cratedb-guide/actions/runs/17181695121/job/48744932084?pr=233#step:4:409
-- https://github.com/crate/crate-docs-theme/actions/runs/17176318205/job/48736558398?pr=621#step:7:441
- GH-553

Start ignoring RTD API errors in compatibility layer
